name: publish

# Is activate manually
#  workflow_dispatch:
on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      ## Install and build website
      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install
        run: npm ci
      - name: Run predeploy
        run: npm run predeploy

      ## Docker login to github and build / push image
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildk
        uses: docker/setup-buildx-action@v1
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./package/Dockerfile
          context: .
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: ghcr.io/${{ github.repository_owner }}/personal-site:latest
